export const TEAM_REGISTRATION = 'TEAM_REGISTRATION';
export const GET_TEAM = 'GET_TEAM';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_TEAM_MEMBERS = 'GET_TEAM_MEMBERS';
export const DELETE_TEAM_MEMBER = 'DELETE_TEAM_MEMBER';
export const ADD_TEAM_MEMBER = 'ADD_TEAM_MEMBER'
export const ADD_TEAM_HERO = 'ADD_TEAM_HERO'
export const LOGOUT_TEAM = 'LOGOUT_TEAM'